# enable ES6
parserOptions:
  ecmaVersion: 6
  sourceType: "module"
  ecmaFeatures:
    jsx: true # enable React's JSX

# register plugins
plugins:
  - meteor

# use the rules of eslint-config-airbnb
# and the recommended rules of eslint-plugin-meteor
extends:
  - airbnb/base
  - plugin:meteor/recommended

# registerenvironments
env:
  meteor: true
  browser: true
  node: true
  

rules:
  # eslint
  no-param-reassign: 0
  no-use-before-define: [2, {functions: false, classes: true}]
  no-underscore-dangle: [2, {allow: ["_id"]}]
  object-shorthand: 
    - error
    - always
    - avoidQuotes: false

  # eslint-plugin-meteor
  meteor/template-names: 0

  # eslint-plugin-import
  import/no-unresolved: 0
  import/no-extraneous-dependencies: 0

globals:
  # collections
  Foo: false
  Bar: false

  # packages
  d3: false #d3js:js